### PR TITLE
Cherry-pick the c5fa135 commit

### PR DESCRIPTION
**Pull request by valasatava**

### CODE REVIEW

**Comment by lafita** [comment]
Tests of the BioJava-4 version are failing due to URL changes (file downloads), I think due to the change to HTTPS of the RCSB. 

This is another point in favour of #606. We should port the commits that address these changes to the bugfixes branch.

**Comment by josemduarte** [comment]
It's really just a tiny extension to the API. We need it to properly support software pipelines related to uniprot mapping that depended on 4.2.x

**Comment by lafita** [comment]
Alright sounds good! I was just wondering because I remember it was really hard to get the gaps from the biojava alignments.

**Comment by valasatava** [comment]
There is a pull request #491 included but that’s not entirely on purpose…I added it while merging in some functionality needed by uniprot project and we decided to keep it.

If it’s ready for release we just keep keeping it.

Yana

**Pull request merged**
