### PR TITLE
Extend and Merge the biojava-phylo module

### PR DESCRIPTION
**Pull request by lafita**
The modifications are:
- Use biojava `SubstitutionMatrix` data structures and methods. Eliminate the Jalview code (named `ScoreMatrix`) that was intended for this (redundant).
- Make names consistent: `TreeType` contains the optimization criteria (score) and `TreeConstructorType` contains the clustering algorithm.
- Factor out the distance matrix calculation from the `TreeConstructor`. The user can use any distance matrix. The `TreeType` is also factored out, but only Neighbor Joining is available.
- Remove the `TreeConstructorListeners`, replaced by individual logging in each class (they were not listeners in the first place, because they only created logger messages when called).
- Use least squares error (LSE) instead of the L1 norm error in the `DistanceTreeEvaluator` (convention in the literature).

The new features are:
- Implement new functions to calculate evolutionary distances from an MSA (sequence) or MStA (structure). New functions are: Kimura and Poisson corrections, dissimilarity score (based on Substitution Matrix, it was already implemented in **alignment** module) and structural distance (based on RMSD and diffusion model of protein structures, Gishin 1995).
- Create Wrapper functions for forester-biojava conversion.
- Create a demo (obtained from the `CookBook`) and tests.

The tests will fail until the forester version is updated to the newest version #350, so they are skipped.
This closes issue #346, but it leaves open the issue whether **phylo** and **alignment** modules should be joined.

### CODE REVIEW

**Comment by josemduarte** [comment]
Thanks, this is awesome! I'm going to look into fixing the forester issue. After that we really need to decide whether we join **phylo** and **alignment**.

**Comment by andreasprlic** [comment]
we are waiting for #350 to be resolved before making this merge, right?

**Comment by andreasprlic** [comment]
Actually, It is better to keep pull requests small, so we can be more atomic about moving forward. I think we should have discussed the merge between alignment and phylo modules some more. I'd prefer if the alignment module does not get dependent on forester. (see #346)

**Comment by lafita** [comment]
The major part of the changes are renaming and reorganizing the existing code. I agree that I should have waited for commit 2f9c652. After my comment in #346 (alignment already depends on forester), do you @andreasprlic still think we need to take the commit out?

We need #350 for the tests, because they are now skipped. I tried with the new version and they all pass. So this could be merged and when #350 is resolved, we remove the *Skip* tags of the tests.

**Comment by lafita** [comment]
This pull request has been refactored into extending #370 and merging phylo. The latter has still to be discussed.

**Pull request closed without merging**
