### PR TITLE
Symmetry Axes Refactoring

### PR DESCRIPTION
**Pull request by lafita**
Improvement of the internal representation of symmetry axes for hierarchical symmetry cases (multiple axes of symmetry).

### CODE REVIEW

**Comment by lafita** [comment]
It should also be merged into **biojava-master**.

**Comment by andreasprlic** [comment]
cool stuff! can you merge into -master?

**Comment by josemduarte** [comment]
I'm trying to merge bugfixes-4.2 into master, there's a few conflicts that I'm trying to solve. If I don't manage I'll leave it to you to give it a go @lafita

**Comment by josemduarte** [comment]
Alright it is complicated, there's conflicts both from this PR and from #504 and #508 . @lafita if you could give it a go that'd be great.

**Comment by sbliven** [comment]
Merged.

**Pull request merged**
