### PR TITLE
Fixing the flakiness caused by testGetProteinSequenceForStructure

### PR DESCRIPTION
**Pull request by Vidishab18**
As part of our course project CS527 at UIUC, we chose to fix flaky tests in Biojava project. Flaky tests are those tests that pass and fail without any code changes [https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359]. Flaky tests are can be quite costly since they often require engineers to re-trigger entire builds on CI and often waste a lot of time waiting for new builds to complete successfully.

We used the NonDex tool to find flaky tests [ https://github.com/TestingResearchIllinois/NonDex ] . This is a tool developed in our research lab and has been widely accepted.

Iterating through the hashmap for entries is non-deterministic in nature, so we changed the HashMap to a LinkedHashMap and re-ran the test. The Junits were executed again and they passed. We ran the NonDex tool again and we observed that  flakiness caused due to the test disappears.

### CODE REVIEW

**Comment by josemduarte** [comment]
It doesn't look like the order is important for that particular Map. There's no assumptions on ordering in the code as far as I can tell.

Also I have tried the test `StructureSequenceMatcher.getProteinSequenceForStructure()` a few times and it does not fail. Would you have an scenario and details (stack trace) where it fails?

**Comment by Vidishab18** [comment]
This is the control flow of the program that we observe where in case the iteration order is altered, it can cause a failed test.
 
```
StructureSequenceMatcherTest#testGetProteinSequenceForStructure
....
Map<Integer,Group> groupIndexPos = new HashMap<Integer,Group>(); [Line 136]
		ProteinSequence prot = StructureSequenceMatcher.getProteinSequenceForStructure(struct1, groupIndexPos);
....
StructureSequenceMatcher#getProteinSequenceForStructure [Line 112]
.....
for(Integer seqIndex : chainIndexPosition.keySet()) { [Line 131]
				Integer groupIndex = chainIndexPosition.get(seqIndex);
				groupIndexPosition.put(prevLen + seqIndex, groups.get(groupIndex));
.....
			}
```

The Oracle specification about HashMap says that "This class makes no guarantees as to the order of the map; in particular, it does not guarantee that the order will remain constant over time." The documentation is here for your reference:https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html

The retrieval of the elements using keySet() can be non-deterministic for a HashMap and can cause StructureSequenceMatcherTest#getProteinSequenceForStructure to be a flaky test.

This is the error that the failed run of the StructureSequenceMatcherTest shows :
```
INFO: Surefire failed when running tests for G12OUwVtxdaLpQYXyiFcgBXgp1UIczplMnT0nJjTZHo=
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=455
nondexEnd=455
nondexPrintstack=true
nondexDir=/home/vidisha2/biojava/biojava-structure/.nondex
nondexJarDir=/home/vidisha2/biojava/biojava-structure/.nondex
nondexExecid=ugiWXsCJBo1zVV7iXWc46SVIRh26TYVHQRcDYUF2Y=
nondexLogging=CONFIG
test=org.biojava.nbio.structure.io.StructureSequenceMatcherTest#testGetProteinSequenceForStructure
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.biojava.nbio.structure.io.StructureSequenceMatcherTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.204 s <<< FAILURE! - in org.biojava.nbio.structure.io.StructureSequenceMatcherTest
[ERROR] testGetProteinSequenceForStructure(org.biojava.nbio.structure.io.StructureSequenceMatcherTest)  Time elapsed: 1.203 s  <<< FAILURE!
org.junit.ComparisonFailure: Modified residues expected:<[IVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASNRPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFKSAEDCMRTCGGA]> but was:<[RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFKSAEDCMRTCGGAIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN]>
	at org.biojava.nbio.structure.io.StructureSequenceMatcherTest.testGetProteinSequenceForStructure(StructureSequenceMatcherTest.java:142)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StructureSequenceMatcherTest.testGetProteinSequenceForStructure:142 Modified residues expected:<[IVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASNRPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFKSAEDCMRTCGGA]> but was:<[RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFKSAEDCMRTCGGAIVGGYTCGANTVPYQVSLNSGYHFCGGSLINSQWVVSAAHCYKSGIQVRLGEDNINVVEGNEQFISASKSIVHPSYNSNTLNNDIMLIKLKSAASLNSRVASISLPTSCASAGTQCLISGWGNTKSSGTSYPDVLKCLKAPILSDSSCKSAYPGQITSNMFCAGYLEGGKDSCQGDSGGPVVCSGKLQGIVSWGSGCAQKNKPGVYTKVCNYVSWIKQTIASN]>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```


Using our tool, we ran various iterations of this test and we were able to figure out the failure
This is the stack trace of the run : 
```
TEST: org.biojava.nbio.structure.io.StructureSequenceMatcherTest#testGetProteinSequenceForStructure
java.lang.Thread.getStackTrace(Thread.java:1559)
edu.illinois.nondex.common.NonDex.printStackTraceIfUniqueDebugPoint(NonDex.java:165)
edu.illinois.nondex.common.NonDex.shouldExplore(NonDex.java:136)
edu.illinois.nondex.common.NonDex.getPermutation(NonDex.java:106)
edu.illinois.nondex.shuffling.ControlNondeterminism.shuffle(ControlNondeterminism.java:63)
java.util.HashMap$HashIterator$HashIteratorShuffler.<init>(Unknown Source)
java.util.HashMap$HashIterator.<init>(HashMap.java:1435)
java.util.HashMap$ValueIterator.<init>(HashMap.java:1472)
java.util.HashMap$Values.iterator(HashMap.java:968)
....
org.biojava.nbio.structure.SubstructureIdentifier.loadStructure(SubstructureIdentifier.java:296)
org.biojava.nbio.structure.align.client.StructureName.loadStructure(StructureName.java:509)
org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:503)
org.biojava.nbio.structure.align.util.AtomCache.getStructure(AtomCache.java:487)
org.biojava.nbio.structure.io.StructureSequenceMatcherTest.setUp(StructureSequenceMatcherTest.java:54)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
....
org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```


The original tests may fail or pass without any changes made to the source code and cannot serve as good regression tests. The fix is to use LinkedHashMap instead of HashMap so that the non-deterministic iteration order of HashMap is eliminated and the tests will become more stable.

**Comment by sbliven** [comment]
This method should return a generic Map without regard to the order. If your tool is correct that the test depends on the order, then this is a bug in how the test was written rather than a bug in the API. Can you determine where the order dependence comes from?

I'm curious about how the tool works. Is it changing the HashMap implementation to deliberately break the enumeration order? There's not much info on the github page for the tool.

**Comment by vidishab** [comment]
> This is a bug in how the test was written rather than a bug in the API.

Thank you for the hint. We found that the fix can be done elsewhere. Without the fix, not only this test `org.biojava.nbio.structure.io.StructureSequenceMatcherTest#testGetProteinSequenceForStructure` fails but also other tests: 
`org.biojava.nbio.structure.io.FastaAFPChainConverterTest#testFromFasta`
`org.biojava.nbio.structure.secstruc.TestSecStrucCalc#testMultiModelPred`
`org.biojava.nbio.structure.secstruc.TestSecStrucCalc#testSecStrucPred`
`org.biojava.nbio.structure.align.util.AtomCacheTest#testGetStructureForChainlessDomains`
`org.biojava.nbio.structure.basepairs.TestBasePairParameters#testBasePair`
`org.biojava.nbio.structure.cluster.TestSubunitCluster#testMergeStructure`
`org.biojava.nbio.structure.cluster.TestSubunitExtractor#testHistone`
`org.biojava.nbio.structure.TestParsingCalcium#testCalciumParsing`
`org.biojava.nbio.structure.AtomPositionMapTest#testChains`

> Can you determine where the order dependence comes from?

The order dependence starts from `MmtfStructureReader` that creates a list of `HashMap` objects (in `setModelInfo`) and iterates over those maps in `finalizeStructure`. Due to the non-deterministic order of iteration, it can be produce different structures.

> Is [the tool] changing the HashMap implementation to deliberately break the enumeration order?

Yes, indeed. NonDex tool intentionally changes `HashMap` to randomize the order of elements to simulate what a different implementation may do (e.g., on a future version of Java or even in a current version on another platform).

**Review by josemduarte — APPROVED** [review]
Thanks a lot, now it makes sense. The issue was probably harmless (order of chain addition to Structure should not matter), but still it does sound like a good idea to keep a more deterministic behaviour.

**Comment by Vidishab18** [comment]
@josemduarte The Travis CI seems to be failing. 
Is there anything else I need to do from my end for this PR ?.

**Comment by josemduarte** [comment]
The failures are unrelated. Some of them are due to an issue that is fixed in master already. 

Could you merge master into your branch and push it? That will then run the tests with all the latest changes.

**Comment by Vidishab18** [comment]
@josemduarte I merged the master and pushed it. I guess Travis CI is failing for an Assertion test in biojava-integrationtest module.

**Review by sbliven — APPROVED** [review]
OK, ensuring predictable chain enumeration seems like a good idea. Thanks!

**Comment by Vidishab18** [comment]
@sbliven @josemduarte 
Thank you . Is the PR now good to be merged ?

**Comment by josemduarte** [comment]
Thanks for merging master. Now that the tests ran, there is an integration test that has failed and it seems to be due to chain ordering (so related to this fix). I think that requires fixing the test. I'll do that after merging this.

**Pull request merged**
