### PR TITLE
Modified PDBParser to fix bug #330

### PR DESCRIPTION
**Pull request by sroughley**
The PDBFileParser has been modified to ensure that all lines are right-padded to 80 characters prior to parsing to prevent certain parsers failing if the line is shorter than the position of some of the later optional fields, e.g. in DBRef

### CODE REVIEW

**Comment by josemduarte** [comment]
This looks great! My only comment is that with the new padding there is a lot of redundant checks for length of line in the rest of the parser. It should be possible to make it slightly more efficient by removing those extra checks. Anyway that would be a marginal gain.

**Comment by sroughley** [comment]
OK, I will try to track as many of those down as possible and remove them

**Comment by sbliven** [comment]
Wouldn't it make more sense to add additional checks for the length, rather than padding with spaces and then trimming each field down to nothing?

**Comment by andreasprlic** [comment]
The discussion here has not been active in some time. As such I am giving this a ping. I am actually with @sbliven . Rather than inflating the length of the Strings, I'd prefer more checks for the correct lengths. where needed.

**Comment by sroughley** [comment]
I think there are potentially two issues here, which are closely related.  The PDB format requires 80 character lines, even if in many cases not all 80 characters are used.  In the case of the DBRef#toPDB() call, the 'writer' had a #trim() call at the end of the method which removed trailing spaces, with the effect that a broken DBREF line was written when some of the last fields in the line were blank.  Other methods (I think TITLE was one) also write shorter lines than they should.

It was for these reason that I chose to right-pad to the "correct" length as a pragmatic solution.  Obviously, we could assume that either a short line is incorrect and throw a parsing exception, and check and fix all #toPDB() methods through Biojava - probably the most "correct" method, or for each parser method handle short lines accordingly (e.g. either decide that a field which is beyond the end of the supplied line is actually populated by blank spaces, and treat it accordingly, or decide that the line is non-parsable, and again throw a parsing exception).

Any thoughts?

**Comment by josemduarte** [comment]
Whatever the solution to this, I don't think we should be very strict with padding spaces at parsing time. I.e. if a line is correct (it contains all necessary information) but is not padded with spaces until column 80 we should still parse it. 

Many files produced by other softwares (other than official PDB files) don't have all the padding spaces and we really want to be able to parse them as long as everything else is correct (see issue #305 in relation with parsing non-deposited PDB files).

**Comment by sroughley** [comment]
How about having an option on the parser "Allow short lines", which defaults to 'true'.

In this case (i.e. the option is 'true'), wherever possible, short lines are parsed.  I think the simplest way of achieving this is to right pad with spaces.  Some lines will then fail to parse if there are fields with spaces which do not translate to some sort of default or optional value.

If the user decides to set the flag to 'false', i.e. this requires a 'strict' PDB format of 80 characters, then any line which isnt long enough (do we check for length < 80 chars, or just that all fields are within the length?) then a parsing exception is thrown

Finally, I think we should then make sure that all toPDB() methods do return 80 chars

**Comment by josemduarte** [comment]
Rather than introducing another parsing mode (which adds maintenance overhead), I'd rather do something like produce a warning when lines are not padded correctly. In my opinion the padding issue is really not important enough to deserve an exception, especially noting that the PDB file format should be considered already a legacy format and thus it's only of secondary importance.

+1 to all `toPDB()` methods to return 80 chars

**Comment by sbliven** [comment]
So to close this issue, would it be ok if I merge 07de4bb (the DBRef stuff) while omitting the changes to PDBFileParser? If there are still cases where the parser fails then we can fix them individually with bounds-checks.

**Comment by andreasprlic** [comment]
That would be a good way to take this forward.

**Comment by sroughley** [comment]
OK - let's go with that and see where and if problems remain

**Pull request merged**
