### PR TITLE
Fix container inefficiency in GenericFastaHeaderParser.java

### PR DESCRIPTION
**Pull request by cinsttool**
Hi,

We find that there exist container inefficiency in GenericFastaHeaderParser.java.

In particular, at lines 96 and 97 in GenericFastaHeaderParser.java, the for loop keep allocating the `data` array and transform container object `values` to array, which incurs redundant memory allocation and container operations.

We discovered the above containers inefficiencies by our tool cinst. The patch is submitted. Could you please check and accept it? We have tested the patch on our PC. The patched program works well.

### CODE REVIEW

**Comment by cinsttool** [comment]
We cannot figure out why the CI is failing because the error still occurs even after we undo the patch.

**Comment by aalhossary** [comment]
The PR looks good to me.
The error log is 
```
Error:  Failures: 
Error:    TestQuaternaryStructureProviders.test5LDH:69 Bioassembly 3 for PDB id 5LDH should fail with a StructureException!
Error:    TestQuaternaryStructureProviders.testGetNrBioAssemblies5LDH:104 There should be 4 bioassemblies for 5LDH, see github issue #230 expected:<4> but was:<1>
```
Which does not look relevant here.

**Review by josemduarte — APPROVED** [review]
LGTM thanks

The test problems is unrelated. I'll push a fix to master.

**Comment by josemduarte** [comment]
Could you merge master into your branch to trigger the tests again?

**Comment by cinsttool** [comment]
We could not pass the biojava-integrationtest.

The error log is
```
2024-04-10T16:06:21.2084227Z 15:56:19 [main] WARN  org.biojava.nbio.core.util.FileDownloadUtils - could not find expected file size for resource http://prodata.swmed.edu/ecod/distributions/ecod.develop204.domains.txt.
2024-04-10T16:06:21.2092790Z 16:06:21 [main] WARN  org.biojava.nbio.structure.ecod.EcodFactory - Could not get Ecod version, or file is corrupted
2024-04-10T16:06:21.2094379Z java.net.SocketTimeoutException: Connect timed out
```

Maybe `http://prodata.swmed.edu/ecod/distributions/ecod.develop204.domains.txt` is unavailable.

**Comment by josemduarte** [comment]
> Maybe http://prodata.swmed.edu/ecod/distributions/ecod.develop204.domains.txt is unavailable.

Indeed, it looks like it has been down for many days now. Which is odd. It's a popular resource and there's even a very recent publication about it (https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011586). I'll see if I can contact them.

**Comment by cinsttool** [comment]
> Maybe http://prodata.swmed.edu/ecod/distributions/ecod.develop204.domains.txt is unavailable.

Hi, we have found that this file is re-available.

**Comment by josemduarte** [comment]
Thanks... tests are passing finally!

**Pull request merged**
