### PR TITLE
Change AbstractFeature Qualifiers to a key:Array from key:value (#302)

### PR DESCRIPTION
**Pull request by emckee2006**
change qualifier to list in AbstractFeature. Change FeatureInterface. Change FeatureDbReferenceInfo because it also uses the FeatureInterface. Note: this was not intended and may cause unexpected issues

### CODE REVIEW

**Comment by emckee2006** [comment]
Does this fix the issues from your merge request, Zach?

**Comment by emckee2006** [comment]
Just a reminder that this still needs to be checked over :)

**Comment by josemduarte** [comment]
So if I understand it correctly this is to fix issue #301 and addresses all problems raised in pull request #302. Is that right? (I haven't checked the changes yet, just asking and referencing the appropriate issues). This pull request would then override #302

**Comment by emckee2006** [comment]
I hope so. If not it's hopefully a step in the right direction and can be
amended further, if needed...

**Comment by paolopavan** [comment]
Just a comment: I see that you added location writing logic in a
specific writer
class. Why don't you include this in the apposite class InsdcParser and if
still needed wrap it into GenericInsdcHeaderFormat ? It may improve ease of
maintenance.

Il mercoledì 13 gennaio 2016, emckee2006 <notifications@github.com> ha
scritto:

**Comment by emckee2006** [comment]
That is a good question.  I don't think i added new location writing
logic.  All I did was take the previous PR and improve the generic types,
as we had discussed.

**Comment by paolopavan** [comment]
I see. I improved the InsdcParser class (actually I almost completely
rewrote it) but I was not the original author and it was already there when
I added support for nested location and split. So your part maybe was
already there even if it seems clear to me that the two procedures should
be unified. Ok, if you don't do it before maybe I will in the future.
Thanks!

Il giovedì 14 gennaio 2016, emckee2006 <notifications@github.com> ha
scritto:

**Comment by andreasprlic** [comment]
I think this is at least a step in the right direction, so merging this in.

**Pull request merged**
