### PR TITLE
ResidueRange bug fixes

### PR DESCRIPTION
**Pull request by dmyersturnbull**
a7bd1c4 is an important fix that would be nice to have in a Biojava 4 hotfix after the release.

### CODE REVIEW

**Comment by dmyersturnbull** [comment]
@sbliven The ResidueRange regex doesn't accept "1a4w.I", etc. Should we update it to allow this case? And what about "1a4w.I_" and "1a4w.I_1-"?

**Comment by dmyersturnbull** [comment]
Also, StructureName.parseRanges() is broken because it passes the PDB Id to ResidueRange.parse().

**Comment by andreasprlic** [comment]
do you want me to still pull it into 4.0

**Comment by andreasprlic** [comment]
currently fails with 

java.lang.IllegalArgumentException: Could not understand ResidueRange string 4hhb:1
	at org.biojava.bio.structure.ResidueRange.parse(ResidueRange.java:88)
	at org.biojava.bio.structure.ResidueRange.parseMultiple(ResidueRange.java:101)
	at org.biojava.bio.structure.align.client.StructureName.parseRanges(StructureName.java:54)
	at org.biojava.bio.structure.align.client.StructureName.<init>(StructureName.java:50)
	at org.biojava.bio.structure.align.util.AtomCache.getStructure(AtomCache.java:365)
	at org.biojava.bio.structure.TestAtomCache.testAtomCacheNameParsing(TestAtomCache.java:93)

**Comment by dmyersturnbull** [comment]
That test failed because it was using the syntax "4hhb:1" and "4hhb(A:10-20,A:30-40)" (with parenthesis). I believe we no longer support these, so I disabled the test.

I think we should merge this if @sbliven agrees. He authored these changes for #81 and #248 .

**Comment by andreasprlic** [comment]
java.lang.IllegalArgumentException: Could not understand ResidueRange string ent.gz?args=test
	at org.biojava.bio.structure.ResidueRange.parse(ResidueRange.java:88)
	at org.biojava.bio.structure.ResidueRange.parseMultiple(ResidueRange.java:101)
	at org.biojava.bio.structure.align.client.StructureName.parseRanges(StructureName.java:54)
	at org.biojava.bio.structure.align.client.StructureName.<init>(StructureName.java:50)
	at org.biojava.bio.structure.align.util.AtomCache.getStructure(AtomCache.java:365)
	at org

**Comment by sbliven** [comment]
In principle I'm ok with removing the chains via numbers syntax. It can be re-added in 4.1.0 after my #81 changes get merged, which redo this test case properly.

However, the tests were passing before your changes. Why do you want to add partial ranges? They weren't supported before.

**Comment by dmyersturnbull** [comment]
@sbliven  I didn't add support for partial ranges. The issue was that ResidueRangeAndLength.parse("C_1023-", map) for 2eke returned a range for chain A rather than the expected length for chain C. Also, ResidueRange.parse("%#*&%!@") would return a ResidueRange. To fix this, I did a7bd1c4, which causes an IllegalArgumentException to be thrown when the range regex doesn't match. Unfortunately, this change broke a number of tests, which needed to be fixed.

The related issue was that StructureName.parseRanges() was wrong because it would pass "1hiv.A_1-5" to ResidueRange.parse, which doesn't know what to do with a PDB Id. The tests were passing only because ResidueRange.parse was just returning ResidueRange(null, null, null) rather than throwing an IllegalArgumentException.

**Comment by andreasprlic** [comment]
is it easier to merge this at the same time as #81 for release 4.1 ?

**Comment by sbliven** [comment]
So all these issues are fixed in #81, but I wanted to discuss & test those changes more. Should we revert the 2aaed4769e56 merge too?

**Comment by dmyersturnbull** [comment]
@sbliven For Biojava 4, can we just make StructureName not implement StructureIdentifier and remove its getRanges()? I think that would solve these problems.

**Comment by sbliven** [comment]
I actually spent quite a bit of time converting StructureName to be a catch-all StructureIdentifier. I think it works ok. After the release maybe we can skype re #81. I fixed a lot of these problems here, but it still makes me nervous how fragile string parsing is.

**Comment by sbliven** [comment]
If tests pass I'd say keeping StructureName independent for now is a good solution.

**Comment by dmyersturnbull** [comment]
Looks good to merge now to me.

**Pull request merged**
