### PR TITLE
pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule pmd:ConsecutiveAppendsShouldReuse - Consecutive Appends Should Reuse

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ConsecutiveAppendsShouldReuse

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by andreasprlic** [comment]
Does this code change really offer any performance difference? I'd say that the compiler would take care of doing things like that.

**Comment by m-ezzat** [comment]
Based on the PMD plugin, it has a performance impact, and I see that it's also more clearer for readability.
Here's another reference http://pmd.sourceforge.net/pmd-5.2.0/pmd-java/rules/java/strings.html

**Comment by andreasprlic** [comment]
Thanks. Looking at the PMD page, it claims that this 'can' improve performance, but I could see no further reference, where that information is coming from. Do we have any other sources that describe this? 

As I said above, I'd be surprised if the compiler does not deal with this at compile time.

**Comment by andreasprlic** [comment]
This suggests that there is no difference:

http://programmers.stackexchange.com/questions/173377/java-performance-of-stringbuilder-append-chains

**Comment by m-ezzat** [comment]
No, I actually don't have, and I've seen this resource before, but I'm not sure if this is really true or not, but don't think that it's a fake rule by PMD.

**Comment by andreasprlic** [comment]
I just checked the PMD mailing list archives for a discussion of this topic but I could not find anything there. Perhaps the mailing search interface there is not very useful.

**Comment by andreasprlic** [comment]
I don't think this rule adds much value. However let's review and apply the other rules as discussed in #484 .

**Pull request closed without merging**
