### PR TITLE
Converting junit3 to 4, thanks intellij

### PR DESCRIPTION
**Pull request by josemduarte**
FYI, I'll merge in a while

### CODE REVIEW

**Comment by josemduarte** [comment]
@heuermh  I'd be happy to do it if intellij can do it :) Do you know an intellij shortcut for that?

**Comment by heuermh** [comment]
> Do you know an intellij shortcut for that?

I don't know, but it appears that intellij knew how to do it sometimes.  :)

**Comment by josemduarte** [comment]
It seems that optimize imports won't do it. It rather tries the opposite: changing wildcard to explicit. We'll have to leave this for next release.

**Comment by emckee2006** [comment]
The opposite is better, isn't it? That way you are explicitly listing only
the things you need...

**Comment by lafita** [comment]
@heuermh why is the static wildcard import better?

**Comment by heuermh** [comment]
I most prefer explicit static imports, no matter how many
```java
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import org.junit.Test;

//...
@Test
public void testSomething() {
  assertNull(null);
  assertNotNull(something);
}
```

but would still prefer static wildcard imports
```java
import static org.junit.Assert.*;
import org.junit.Test;

//...
@Test
public void testSomething() {
  assertNull(null);
  assertNotNull(something);
}
```

over non-static imports and qualified assert statements
```java
import org.junit.Assert;
import org.junit.Test;

//...
@Test
public void testSomething() {
  Assert.assertNull(null);
  Assert.assertNotNull(something);
}
```

**Pull request merged**
