### PR TITLE
fixes #1008

### LINKED ISSUE #1008: Test failure on SequenceToolsTest$PermuteCyclic.permuteCyclicPerformance on biojava-core subproject
On the latest release there is a test failure on biojava-core subproject. It seems to be caused by the improvement factor which is below the threshold (5).
> [ERROR] Failures: 
[ERROR]   SequenceToolsTest$PermuteCyclic.permuteCyclicPerformance:77 expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 428, Failures: 1, Errors: 0, Skipped: 8

System.err

> 229
89

### PR DESCRIPTION
**Pull request by richarda23**

### CODE REVIEW

**Review by heuermh — APPROVED** [review]

**Comment by heuermh** [comment]
Looks good to me as is.

We could also simply replace the implementation of `permuteCyclic` with that of `permuteCyclic2`.

**Comment by heuermh** [comment]
Fixes #1008

**Comment by richarda23** [comment]
done

**Comment by heuermh** [comment]
Thank you, @richarda23

**Pull request merged**
