### PR TITLE
Aromaticity calculation (Protein) #1037

### PR DESCRIPTION
**Pull request by simoesrenato**
Calculates the aromaticity value of a protein according to Lobry, 1994.
It is simply the relative frequency of Phe(F)+Trp(W)+Tyr(Y).

### CODE REVIEW

**Comment by simoesrenato** [comment]
This is a missing feature for proteomic analysis. It is based on [BioPython SeqUtils](https://biopython.org/docs/1.76/api/Bio.SeqUtils.ProtParam.html).

**Review by josemduarte — CHANGES_REQUESTED** [review]
Thanks looks good. Only one formatting issue: could you make sure to fix indentation? It looks like it is scrambled in a few places. Are you using an IDE?

**Comment by simoesrenato** [comment]
Yes I can handle it asap. I use Netbeans IDE. Thanks!

**Comment by josemduarte** [comment]
Did you have a chance to fix the formatting yet?

**Comment by josemduarte** [comment]
I'll merge and fix the indentation

**Pull request merged**
