### PR TITLE
Refactoring of structure data model

### PR DESCRIPTION
**Pull request by josemduarte**
This implements what we discussed in issue #469, with commits from @andreasprlic, @abradle and myself.

Some highlights of the changes:
- new data model for the structural data: chains are split into polymeric, non-polymeric and water chains, following the mmCIF data model. Chains can be accessed using both asymIds and author chain ids.
- rewrite of the PDB parser so that the data parsed adheres to the new mmCIF data model now used internally in the biojava data structures. Chains are split into their polymeric and several non-polymeric parts and asym ids are assigned to each of them following the same rules used in mmCIF.
- entities are now created heuristically for all compounds in the files even if entity annotation is not present in PDB or mmCIF files
- discontinued support for: parsing of old PDB files with blank chain ids, parsing of LINK records in PDB files (we do have CONECT records still)
- it is important to note that all downstream code will need to adapt to this whenever operations with chains are performed. Especially calls to `Structure.getChainByPDB` (now deprecated) need to change to `Structure.getPolyChainByPDB` or `Structure.getNonPolyChainByPDB`

Tests are passing but I'm sure many issues still remain, let's try to iron them out slowly as we move forward.

### CODE REVIEW

**Comment by andreasprlic** [comment]
Thanks Jose! Just to add, `Structure.getChainByPDB` should not get removed until we are in the BioJava 6 series (at least)...

**Comment by andreasprlic** [comment]
need to change the signature of all new get*ChainByPDB methods. Response should be a List<Chain> rather than a Chain object.

**Comment by josemduarte** [comment]
I've reverted `List<Chain> getPolyChainsByPDB(authId)` to `getPolyChainByPDB(authId)`, but kept `List<Chain> getNonPolyChainsByPDB(authId)`. The one-to-many relationship only exists for non-polymer chains.

Other than that I've fixed a few more issues with PDB parsing and I think this is ready to be merged.

**Comment by andreasprlic** [comment]
There don't seem to be any major comments on this. I think this one is an important step forward and I will merge this in shortly.

**Pull request merged**
