### PR TITLE
Remove load chem comp info

### LINKED ISSUE #426: loadChemCompInfo system property is used inconsistently
A `loadChemCompInfo` system property (see constant in `PDBFileReader.LOAD_CHEM_COMP_PROPERTY`) is used mostly internally to sign that we should load chemical component descriptions. The property interferes with the chemical component provider mechanism and in it looks like it's doing more bad than good. 

For instance in `ChainImpl.getAtomSequence()` and `ChainImpl.getSeqResSequence()` the chemical components are used only if the property is true, whilst the behaviour should depend on the chemical component provider used. In fact if one removes [this condition](https://github.com/biojava/biojava/blob/ff66c26573022cfba2cfa6a025b58435b5c9a960/biojava-structure/src/main/java/org/biojava/nbio/structure/ChainImpl.java#L608), other bugs surface that were hidden by `loadChemCompInfo` being false.

This relates to issues #313 and #397 

I'm working on a pull request. Maybe it can still go into the 4.2 release.

### PR DESCRIPTION
**Pull request by josemduarte**
This fixes #426 . A few issues were hidden by the loadChemCompInfo setting that I've fixed in the commits below.

### CODE REVIEW

**Comment by andreasprlic** [comment]
This comes in after the code freeze. We can delay the release by a day so this can still get in. However let's review tomorrow and make sure that these changes don't break anything in the last moment:

**Comment by sbliven** [comment]
Seeing as this removes methods, would it be more suited for the 5.0 release anyways?

**Comment by josemduarte** [comment]
The one method that has been removed with this pull request is `FileParsingParameters.setLoadChemCompInfo()`. The effect of calling that was inconsistent (it would switch on/off some chemcomp behavior but not other). I thought it was better to get a compile error so that the BioJava user knows that the method doesn't exist anymore and doesn't do what they'd expect.

Of course I can just put it back and add a deprecation tag to it saying that it doesn't do anything. Would that be preferred?

**Comment by josemduarte** [comment]
To be clear this issue is related to the many we've had with the chemical component framework (#313, #337, #397, #145 ). We've fixed many of them for 4.2 but I feel without this fix the thing would be incomplete and more issues would come in the future. The framework is essential for the functioning of the whole structure module so I think it's worth trying getting this right.

**Comment by lafita** [comment]
I agree with @josemduarte, the behavior of this method was never very clear. There was also an issue reported long ago in the mailing list and a temporal fix was introduced that changed static objects of the **ChemCompFactory** through this method.

However, how would the user deactivate the loading of chemical component information? By manually setting the system property, like:
```java 
System.setProperty(PDBFileReader.LOAD_CHEM_COMP_PROPERTY, "false");
```

**Comment by andreasprlic** [comment]
Travis fails since it seems EBI ftp is not working well. I'll merge this anyways, since  I compiled the branch locally and verified that everything else works as expected.

**Comment by josemduarte** [comment]
One note: when merging #431 into this I had conflicts in all files that I had touched. To solve them quickly I had to accept my versions of the files. That means that those files will not be re-formatted with @sbliven's #431 changes. If we are really concerned about that, the re-formatting scripts would have to be rerun on those.

**Comment by andreasprlic** [comment]
Let's release tomorrow, this is not worth delaying the release.

**Pull request merged**
