### PR TITLE
POM Cleanup: Add Maven descriptors & remove mention of Travis CI

### PR DESCRIPTION
**Pull request by JonStargaryen**
- need Maven descriptors for `pom.properties` files when using BioJava as dependency
- this ensures that they are added to the artifacts

### CODE REVIEW

**Review by josemduarte — APPROVED** [review]
LGTM thanks.

There's an unrelated test failure. It seems due to an obsoleted PDB id. I'll try to push a fix to master, so that then this can be tested.

**Comment by josemduarte** [comment]
Ok I committed a fix: could you merge master in, so that tests run?

**Comment by josemduarte** [comment]
Actually there were a couple more test issues (after recent remediation of some PDB entries). Now I think I fixed them all. Please try again.

**Comment by JonStargaryen** [comment]
Thanks for updating the tests. Let's see how this goes.

**Pull request merged**
