### PR TITLE
Fix modDate

### PR DESCRIPTION
**Pull request by aalhossary**
In case there is only one revision (release), set the modDate to that date.

### CODE REVIEW

**Comment by aalhossary** [comment]
Fixes #992

**Review by JonStargaryen — APPROVED** [review]
Thanks for the fix, LGTM!
One nitpick: Can you please remove the inconsistent indentation on the `pdbHeader.setRelDate(relDate);` lines?

**Comment by aalhossary** [comment]
Interesting that you noticed the inconsistency in the indentation between tab and space.
Did your IDE warn you or you enable white space characters?

**Comment by JonStargaryen** [comment]
> Interesting that you noticed the inconsistency in the indentation between tab and space. Did your IDE warn you or you enable white space characters?

They were rendered differently in the GitHub diffs. Looks like tabs vs whitespaces.

**Comment by aalhossary** [comment]
Yes it was Tab vs space.
Thank you for the tip.

**Review by josemduarte — APPROVED** [review]
LGTM thanks

**Pull request merged**
