### PR TITLE
Updating to latest RCSB URLs for 4.2.x

### PR DESCRIPTION
**Pull request by josemduarte**

### CODE REVIEW

**Comment by lafita** [comment]
Some tests are still failing:

```
Failed tests: 
  ChemCompTest.testChangingProviders:144 expected:<[MEA]> but was:<[???]>
  ChemCompTest.testMEA:72  one letter code is not correct expected:<[F]> but was:<[?]>
  ChemCompTest.testPRR:104 Got back group of wrong type! org.biojava.nbio.structure.HetatomImpl
  TestAsaCalc.testAsa3PIU:69 expected:<17462.0> but was:<17638.907170976614>
  TestParseMmCIFLigands.testLigandConnections:65 expected:<172> but was:<0>
  TestParseMmCIFLigands.testMultipleConformations:109 expected:<114> but was:<0>
```

**Comment by josemduarte** [comment]
Still working on it... Locally it worked ok for me but not in travis, weird.

**Comment by lafita** [comment]
The master branch fails on travis but passes for me locally. I can't tell from the travis log what is going wrong, though.

**Comment by josemduarte** [comment]
Ok it's due to the use of https instead of http. Travis has some different settings for that (or perhaps a different java vm?) and it fails. I'll change to http.

**Pull request merged**
