### PR TITLE
Set release date instead of modification date

### PR DESCRIPTION
**Pull request by pwrose**

### CODE REVIEW

**Comment by josemduarte** [comment]
It seems that the build is failing because of a combination of an old JVM version in Travis plus the RCSB PDB certificates having changed recently (last week). At least this is what I gathered from this post: https://bitbucket.org/versioneye/versioneye/issues/276/ssl-certificate-issues-when-using-maven

It looks like Travis is using a rather old JVM and it doesn't seem possible to change that.

**Comment by josemduarte** [comment]
We've seen this kind of failures in all the latest pull requests in master. Running locally on an Ubuntu box with latest JVM all works fine.

**Comment by josemduarte** [comment]
By the way the error message looks like this (from Travis logs):

```
Running org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.256 sec <<< FAILURE! - in org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance
test3HBX(org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance)  Time elapsed: 1.488 sec  <<< ERROR!
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance.test3HBX(TestMmtfPerformance.java:104)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance.test3HBX(TestMmtfPerformance.java:104)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.biojava.nbio.structure.io.mmtf.TestMmtfPerformance.test3HBX(TestMmtfPerformance.java:104)
```
That's the same as @lafita observed in his latest PR

**Comment by josemduarte** [comment]
I'll merge this, since tests work fine locally.

**Comment by josemduarte** [comment]
Regarding the SSL JVM problems, I've tried changing travis configuration to use openjdk8 but that's not supported yet despite what their docs say: https://docs.travis-ci.com/user/languages/java/

**Comment by josemduarte** [comment]
I've finally managed to fix the outdated JVM problem in travis by using the `sudo: required` environment. Found the solution in this post: https://github.com/travis-ci/travis-ci/issues/3259. Tests should be working now.

**Comment by pwrose** [comment]
Excellent, thanks Jose.

**Pull request merged**
