### PR TITLE
ABITrace test coverage

### PR DESCRIPTION
**Pull request by richarda23**
Added test for ABITrace#getTrace() method, which  lacked test coverage.

Thanks, great project.

### CODE REVIEW

**Review by josemduarte — APPROVED** [review]
Thank you! LGTM

Note that the CI test running from github workflows is not working at the moment. However travis does and all is well there.

**Comment by richarda23** [comment]
no problem - if I do more of these sorts of test improvements, so you prefer more frequent small PRs or less frequent larger ones? Do you have any plans to start using junit5?

**Comment by josemduarte** [comment]
I think PRs should be about a single topic (e.g. a new feature or a bugfix). They can be large if the feature is large. In any case, I think it'd be acceptable to have several unit tests in a certain biojava area packed together.

Regarding junit5 I don't have strong opinions. I think it'd be nice to move forward, but I don't know how much effort would be required to convert the existing tests. I remember that it wasn't difficult for junit3->4 because intellij had an automatic convertor. Is there something similar available for 4->5?

**Comment by richarda23** [comment]
Yes, junit5 has a compatibility layer ('vintage'), so new tests can be written in junit5 and older junit 3/4 tests can be migrated later (or not). We just updated at work, and it's nice to start using test display names, parameterized tests, nested tests etc. Java 8  is required and version 2.22 of maven surefire test runner plugin. 
   
  
  
   
  
  
   If you like I can submit a PR with the pom updates and a few examples, and you can see what you think?
   
  
  
   Richard
   
  
  
   
    On 02/07/2021 22:01 Jose Manuel Duarte ***@***.***> wrote:
   
   
    
   
   
    
   
   
   I think PRs should be about a single topic (e.g. a new feature or a bugfix). They can be large if the feature is large. In any case, I think it'd be acceptable to have several unit tests in a certain biojava area packed together.
   Regarding junit5 I don't have strong opinions. I think it'd be nice to move forward, but I don't know how much effort would be required to convert the existing tests. I remember that it wasn't difficult for junit3->4 because intellij had an automatic convertor. Is there something similar available for 4->5?

**Comment by josemduarte** [comment]
> If you like I can submit a PR with the pom updates and a few examples, and you can see what you think?

That sounds good to me, thanks!

**Pull request merged**
