### PR TITLE
Add more strict tests and fix found problems

### PR DESCRIPTION
**Pull request by jgrzebyta**
* add new InsdcParser. It will replace LocationParserTest.java
* add more strict tests for InsdcParser and GenbankProxySequenceReader
* fixed issue #254
* restore parent sequence inside `ProteinSequence(ProxySequenceReader<AminoAcidCompound>, CompoundSet<AminoAcidCompound>)` constructor

### CODE REVIEW

**Comment by jgrzebyta** [comment]
I found there are another issues. I temporary close my request.

**Comment by jgrzebyta** [comment]
I have added additional tests + fixed small issue in GenbankProxySequenceReader

**Comment by andreasprlic** [comment]
Thanks Jacek!

**Comment by jgrzebyta** [comment]
Merged biojava/biojava@98cc07265172fca9e481c5764ae0efe62dac9db0 so there should not be eny error in biojava-structure tests.

**Pull request merged**
