### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by narmineba**
I am new to the project and I wanted to have my first contribution as adding a Code Of Conduct

### CODE REVIEW

**Comment by brianrepko** [comment]
Thank you @narmineba for this. Is the content of this something that came from another project or from https://opensource.guide/code-of-conduct/ ?

**Comment by brianrepko** [comment]
> Thank you @narmineba for this. Is the content of this something that came from another project or from https://opensource.guide/code-of-conduct/ ?

Ah - read all the way to the bottom of the document, Brian... I see that this is in fact the latest version of the Contributor Covenant.

**Comment by brianrepko** [comment]
Is this something that applies to all the OBF projects?

**Comment by darnells** [comment]
If this were to gain support by the principal maintainers, it is inappropriate for the enforcement point-of-contact to be @narmineba who is new to the project (see line 58).

**Comment by heuermh** [comment]
> ... it is inappropriate for the enforcement point-of-contact to be @narmineba who is new to the project (see line 58).

Agreed.  I believe the two most important parts of the code of conduct are the enforcement and escalation sections.  We've adapted the [Contributor Covenant](https://www.contributor-covenant.org/) in the ADAM and other Big Data Genomics projects per our organizational structure

https://github.com/bigdatagenomics/adam/blob/master/CODE_OF_CONDUCT.md#enforcement
https://github.com/bigdatagenomics/adam/blob/master/CODE_OF_CONDUCT.md#escalation

The Biojava project has a de-facto project leadership team but not an email alias to contact, and I'm not sure if there is a PI or are PIs that would be willing to be the escalation point of contact.

As far as I know there is no discussion about an organization-wide code of conduct for the Open Bioinformatics Foundation member projects.

There was code of conduct for the [BOSC 2018 conference](https://www.open-bio.org/wiki/BOSC), co-organized and co-located with the [GCC 2018 conference](https://gccbosc2018.sched.com/)

https://galaxyproject.org/events/gccbosc2018/code-of-conduct/

As part of ISMB/ECCB 2019, the BOSC 2019 conference will be covered by ISMB's Code of Conduct

https://www.iscb.org/ismbeccb2019-general/codeofconduct

**Comment by narmineba** [comment]
I understand that a new contributer should not be the one responsible for
the Code Of Coduct.
Is there anything I can do to remove it.

Le ven. 22 févr. 2019 à 20:02, Michael L Heuer <notifications@github.com> a
écrit :

**Comment by josemduarte** [comment]
Thanks @narmineba for starting the conversation. 

I agree with others here. It's great to have the code of conduct but the point of contact can't be a user new to the project.

I would support having a common code of conduct for all the OBF projects and a general OBF email address as the common contact point for all the OBF projects. Perhaps something to discuss at BOSC 2019? 

Any opinions from biopython, @peterjc ?

**Comment by peterjc** [comment]
For context, I am one of the Biopython developers and current lead. I am also on the board of the parent organisation
of BioJava and Biopython etc, the Open Bioinformatics Foundation (OBF).

It is good to hear interest in this from the community level. The OBF board has discussed a code of conduct, potentially as a requirement for new member projects, and to be encouraged for existing member projects (BioJava etc). The OBF board could then be a final point of escalation (eg if there was a complaint with the project leadership). Nothing formal as yet.

I will forward this to the OBF board and CC the BioJava leadership (@josemduarte).

**Comment by brianrepko** [comment]
Just want to thank @narmineba for initiating this import conversation!

**Comment by sbliven** [comment]
I would also suggest following OBF's lead on a code of conduct.

**Comment by lafita** [comment]
I am closing this one as it seems that the OBF is on top of it.

**Comment by peterjc** [comment]
This has taken longer than we might have hoped, but there is now a public blog post and OBF issue on this for feedback:

https://www.open-bio.org/2019/11/15/creating-an-obf-wide-code-of-conduct/

https://github.com/OBF/obf-docs/issues/67

**Comment by josemduarte** [comment]
Thanks a lot @peterjc and @yochannah !

I will circulate this in BioJava mailing list too.

**Pull request closed without merging**
