### PR TITLE
StructureIdentifier framework

### PR DESCRIPTION
**Pull request by sbliven**
Add substantially new unified class for identify structures: StructureIdentifier

This unifies various prior methods for identifying a structure from a string, which was
previously spread over AtomCache methods and StructureTools/StructureIO utilities. It
includes PDB IDs, residue range specifications, URLs, SCOP/CATH/PDP domains, and files.

Major Classes:
* StructureIdentifier is an interface for methods which know how to load a structure from
  some resource and reduce it to the requested substructure. The most important property
  is the identifier, which can be an arbitrary string.
* SubstructureIdentifier is considered the canonical way to specify a structure and
  is the major implementation for chain and residue level substructures. All identifiers
  can be converted to a SubstructureIdentifier.
* StructureName is suitable for wrapping user-supplied identifiers, and it dispatches the
  request to a more specific class based on a guess as to the type (PDB, URL, file, etc).

StructureIdentifiers can represent arbitrary strings (e.g. domain IDs). These are converted
(possibly through some relatively slow process like downloading and parsing a file) into
standard-format SubstructureIdentifier instances, which should be easier to serialize and
recreate.

Detailed changes:

* Substantially changes StructureIdentifier, which existed but wasn't used anywhere.
  * Remove getPdbId() method, since not globally relevant. It's still present in most
    implementations, and can always be accessed via toCanonical().getPdbId()
* AtomCache
  * Accept chain indices ("4HHB.0") with a warning if there was not
    already a chain with that ID.
  * Removes support for the strictScop parameter. The new default is effectively strictScop=false. This can be overridden by getting a ScopDomain directly from a particular ScopDatabase, rather than using generic methods like AtomCache.getStructure(String), which use the StructureName class for fuzzy matching of domain names.
* Better guessing of PDB/CIF filetypes from filename (but not full autodetection from contents, as requested in #232)

### CODE REVIEW

**Comment by sbliven** [comment]
I'd welcome a code review of this pull. Particularly, what should the return type for getCanonical() be? Ideally, it would be an identifier capable of representing arbitrary selections from a structure. Currently, the best we have is an identifier capable of representing residue ranges (SubstructureIdentifier).

**Comment by josemduarte** [comment]
Travis is failing, is that some networking issue?

I'll give a look at the code when I get a bit of time. Thanks for the pull request, this looks awesome!

A question, this would support multi-letter chain identifiers, wouldn't it?

**Comment by sbliven** [comment]
Tests pass on my laptop, but there are plenty of changes here. I'll restart Travis and double check.

**Comment by lafita** [comment]
There is a Test in the core module that sometimes gives a network exception from Travis. Is it the case?

**Comment by lafita** [comment]
The error is in the test files I created for MultipleAlignment serialization (XML, FASTA, etc), because the names of the structures do not match (that is expected from your changes @sbliven). We just need to update the files with the new names.

**Comment by sbliven** [comment]
Ok, finally fixed the minor test regressions and got travis to finish the tests.

**Comment by sbliven** [comment]
I'm going to merge this before master diverges too much. Comments about the new code are still appreciated.

**Pull request merged**
