### PR TITLE
Add methods for reading RNA sequences.

### PR DESCRIPTION
**Pull request by heuermh**
Added methods for reading RNA sequences by copy paste search replace.

### CODE REVIEW

**Comment by josemduarte** [comment]
There are some issues with the tests, most likely unrelated to this. I'll try restarting them again.

**Comment by lafita** [comment]
I think the errors are with CATH tests (a NPE). I will run the tests locally to see if they pass.

Also, could we add some tests for the new methods? Just copying the DNA tests and replacing them with RNA would be enough.

**Comment by lafita** [comment]
Tests pass locally and I see that also in travis. Looks ok to me although would be nice to include the tests.

**Comment by heuermh** [comment]
Sure, I can add some tests.  I was hunting for some Genbank RNA files in the wild but I couldn't find any, they aren't usually represented that way.

**Comment by lafita** [comment]
Do you mean an RNA database? I know about RNAcentral for non-coding RNA sequences http://rnacentral.org

**Comment by heuermh** [comment]
Specifically I meant Genbank sequences using the RNA alphabet.  You can find FASTA formatted RNA sequences in the RNA alphabet in some of those databases, but Genbank RNA sequences (like AY892647.1 you linked) are represented in the DNA alphabet.

**Comment by lafita** [comment]
True, I wonder why though! Seems that a simple U for T replacement is needed.

**Comment by josemduarte** [comment]
So it seems that we can't have an RNA file for the test, right? I'll merge for the moment, but it'd be good to have a test at some point.

**Pull request merged**
