### PR TITLE
Implementing new crystallographic metadata fields.

### PR DESCRIPTION
**Pull request by josemduarte**
A follow up of #604. A minor addition: 2 new methods in PDBCrystallographicInfo to check for non-standard space groups and coordinate frame convention. I've created a more comprehensive test and moved it from structure module to integrationtest module.

### CODE REVIEW

**Comment by josemduarte** [comment]
I'm intending to add this to bugfixes-4.2 if there's nothing against it.

**Comment by josemduarte** [comment]
Well one can store the SG string and the matrix or store the booleans instead. Storing the booleans seems better in terms of simplicity of code and memory footprint. It only adds a (minimal) overhead of checking things at parse time.

**Comment by josemduarte** [comment]
Regarding PDB format files: I've now pushed a commit that handles non-standard space groups when loading from PDB format file. But I didn't do the same for the scale matrix check because it requires implementing the parsing of that record. Anyway this checks only apply to old PDB-deposited files and we should only use mmCIF format for those archival files. For non-deposited files coming from users this non-standard things are not a concern at all, since the softwares that produced them are long dead.

**Comment by sbliven** [comment]
Merged to master, but I'll leave the cherry-pick to @josemduarte

**Comment by josemduarte** [comment]
Thanks! I've done the cherry-pick.

**Comment by andreasprlic** [comment]
cool, thanks!

**Pull request merged**
