### PR TITLE
Test atom cache parsing flags

### PR DESCRIPTION
**Pull request by andreasprlic**

### CODE REVIEW

**Comment by andreasprlic** [comment]
This fixes a bug with setting the correct file type to use in AtomCache. Previously: both mmtf and mmcif flags were set to true.

**Comment by josemduarte** [comment]
This seems to contain PR #576 too, should we close that one and keep both fixes together here?

**Comment by andreasprlic** [comment]
Ah yes, you could just merge this one and close both...

**Comment by andreasprlic** [comment]
I reverted the changes in AlignmentTools to the version of the master branch.

**Pull request merged**
