### PR TITLE
Update dependency versions for guava, slf4j, and log4j.

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by heuermh** [comment]
```
Tests in error: 
  SiftsChainToUniprotMappingTest.test:41 » Connect Connection timed out (Connect...
```
I retriggered the Travis build manually.

**Comment by emckee2006** [comment]
While dependencies are being fixed, is there any way to fix the Forrester
invalid pom issue?

**Comment by heuermh** [comment]
> While dependencies are being fixed, is there any way to fix the Forrester invalid pom issue?

I don't know what that is, do you have a link?

**Comment by josemduarte** [comment]
@emckee2006 the forester story is like this: it was a dependency of biojava for a long time. The project was very old and not under active development anymore, it also wasn't mavenised. A couple of years ago @lafita made a few important bugfixes to it and in order to include it in biojava, I [forked it](https://github.com/josemduarte/forester) and mavenised it, including the bugfixes. The original developer never replied to my requests.

In that mavenisation, I couldn't find one of the dependencies (openchart) in maven central so in the end I had to include the jar file within the project. That's were the warning comes. See the relevant lines in pom file here:

https://github.com/josemduarte/forester/blob/bf4dce83213e5d873d9f8d8087c473a6706b41fb/pom.xml#L58:L67

Is there an easy alternative solution for this?

**Comment by emckee2006** [comment]
is that something that you mark as provided or run time

**Comment by josemduarte** [comment]
Is marked as scope=system. Copying here the lines linked above:
```xml
<!-- Openchart is not available in maven central. The only way we can provide 
			it is by pointing to the jar within the distribution. That's not ideal and 
			maven warns about it. -->
		<dependency>
			<artifactId>openchart</artifactId>
			<groupId>openchart</groupId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/src/main/resources/openchart.jar</systemPath>
		</dependency>
```

**Comment by josemduarte** [comment]
I've tested locally and all worked fine. I'll merge it.

**Comment by heuermh** [comment]
Thanks!

**Comment by emckee2006** [comment]
Would this trick make the complaint go away?
http://randomizedsort.blogspot.com/2011/10/configuring-maven-to-use-local-library.html?m=1

**Pull request merged**
