### PR TITLE
Proposed fix for #355

### PR DESCRIPTION
**Pull request by andviane**
Interval intersection is wrongly computed. Here is the proposed alternative implementation. It passes the new TestIssue355 Unit test that exists in another branch.

### CODE REVIEW

**Comment by andviane** [comment]
The second 'Cleanup' commit was only intended to restore the by chance applied formatting, without any changes in the code itself. Really no idea why it failed. Maybe something system dependent? There are messages about the PDB_DIR property being accessible during the build.

**Comment by josemduarte** [comment]
Thanks! Could you merge in the TestIssue355 branch? or otherwise simply add the test manually? We need to make sure that the test always runs. I suspect Travis failures are related to some download problem. Let´s see if it builds after you push another commit.

**Comment by andviane** [comment]
Ok done.

**Comment by josemduarte** [comment]
Thanks! I'll merge it

**Comment by josemduarte** [comment]
We'll need to add this to the bugfixes branch too

**Pull request merged**
