### PR TITLE
Adding CONECT information when parsing mmCIF files.

### PR DESCRIPTION
**Pull request by larsonmattr**
These changes are for addressing and closing issue #341 (creating CONECT information when parsing mmCIF).  

FileParsingParameters is updated to include an option setCreateLigandConects(true/false) that enables creating CONECT-style records for ligand groups in a Structure.

SimpleMMcifConsumer, when isCreateLigandConects() will build CONECT-style records and use a new LigandConnectMaker class to find and create CONECT records for all ligands in a Structure.  This relies on ChemComp groups to supply the missing bond information (mmCIF, unlike PDB, do not include this in the file normally).  Along with the mechanism of DownloadChemCompProvider or other ChemComp provider this provides an automatic way to annotate the ligand bonds.

The PDBFileParser likewise recognizes the isCreateLigandConects(), and fill in missing CONECT bonds for ligand groups based on the ChemComp information.  This can be useful for minimal ATOM-only PDB files that need to add bond information.

Also, there are two tests: 
1 unit test that mmCIF parses Bonds for common ligands like in PDB:4HHB
1 unit test that mmCIF parses Bonds for a ligand in PDB:3UCB that has alt. conformations.

### CODE REVIEW

**Comment by larsonmattr** [comment]
All tests passed locally, and it is unclear why Travis has an error in biojava-integrationtest with BerkeleyScopInstallationTest>ScopDatabaseTest.testCategories

**Comment by andreasprlic** [comment]
I see a org.biojava.nbio.structure.scop.ScopIOException: java.io.IOException: Can't parse line d3spbb_	
Caused by: java.io.IOException: Can't parse line d3spbb_

Are your locally cached files the latest version?

**Comment by larsonmattr** [comment]
It may have tripped travis because it failed to download dir.com.scop.txt_2.05 from the SCOP_DOWNLOAD site.  

I've merged in the recent changes from the last pull, and checks pass.

**Comment by andreasprlic** [comment]
yes, was prob a temporary networking issue at Travis..

**Comment by andreasprlic** [comment]
I accepted the merge. One thing to think about still is if this behaviour should be turned on by default.

**Pull request merged**
