### PR TITLE
Added support for feature parsing from the genbank file. 

### PR DESCRIPTION
**Pull request by paolopavan**
It supports also qualifiers and complex nested locations

### CODE REVIEW

**Comment by andreasprlic** [comment]
Thanks Paolo. I can now see the various commits from you and @jgrzebyta . The latest merge https://github.com/paolopavan/biojava/commit/d92df43b0a9c2b8b27ba9654e6d29d38a31b6071 contains 509 modified files. I see if I can change this to a rebase...

**Comment by sbliven** [comment]
@andreasprlic Ok, I see what you mean now about the large merge commit. I'm not convinced it's a problem, since most of the files were touched on the biojava side of the merge. A rebase is certainly possible. Should we close this and pull from my rebased `genbank` branch instead (20bf42f)?

**Comment by andreasprlic** [comment]
Thanks @paolopavan , @jgrzebyta , and @sbliven  for your help!

**Comment by jgrzebyta** [comment]
Thats ok.

**Pull request merged**
