### PR TITLE
Fix for issue 544

### PR DESCRIPTION
**Pull request by josemduarte**
This should fix the test problems for the moment. I didn't get a reply from cath yet, so don't know if the old URL is gone for good. In any case the new server layout seems to be well thought and solid, it looks like it is there to stay. One problem is I couldn't find the new file names for CathDomainDescriptionFile and CathNames, so that's a TODO for later.

### CODE REVIEW

**Comment by andreasprlic** [comment]
thanks!

**Comment by lafita** [comment]
Thank you @josemduarte!

**CathDomainDescriptionFile**: http://download.cathdb.info/cath/releases/latest-release/v4_1_0/cath-classification-data/cath-domain-description-file-v4_1_0.txt
**CathNames**: http://download.cathdb.info/cath/releases/latest-release/v4_1_0/cath-classification-data/cath-names-v4_1_0.txt

I will make a direct commit to master with the names.

Should we include these changes to 4.2-bugfixes branch too?

**Comment by andreasprlic** [comment]
Yes, I think that would be useful

**Comment by josemduarte** [comment]
Thanks @lafita , I've just cherry-picked it back to bugfixes-4.2. There should be a release with all this later today.

**Pull request merged**
